//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  siteData: SiteData;
  siteDataConnection: SiteDataConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteDataArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteDataConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteDataFilter>;
};

export type DocumentFilter = {
  siteData?: InputMaybe<SiteDataFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = SiteData | Folder;

export type SiteDataHero = {
  __typename?: 'SiteDataHero';
  title_line1: Scalars['String']['output'];
  title_line2: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type SiteDataProblems = {
  __typename?: 'SiteDataProblems';
  title: Scalars['String']['output'];
  desc?: Maybe<Scalars['String']['output']>;
};

export type SiteDataApproachSteps = {
  __typename?: 'SiteDataApproachSteps';
  number?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  desc?: Maybe<Scalars['String']['output']>;
};

export type SiteDataApproach = {
  __typename?: 'SiteDataApproach';
  steps?: Maybe<Array<Maybe<SiteDataApproachSteps>>>;
  note?: Maybe<Scalars['String']['output']>;
};

export type SiteDataSolutions = {
  __typename?: 'SiteDataSolutions';
  title: Scalars['String']['output'];
  desc?: Maybe<Scalars['String']['output']>;
};

export type SiteDataRegions = {
  __typename?: 'SiteDataRegions';
  name: Scalars['String']['output'];
  desc?: Maybe<Scalars['String']['output']>;
};

export type SiteDataContact = {
  __typename?: 'SiteDataContact';
  email?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  whatsapp?: Maybe<Scalars['String']['output']>;
};

export type SiteData = Node & Document & {
  __typename?: 'SiteData';
  hero?: Maybe<SiteDataHero>;
  problems?: Maybe<Array<Maybe<SiteDataProblems>>>;
  approach?: Maybe<SiteDataApproach>;
  solutions?: Maybe<Array<Maybe<SiteDataSolutions>>>;
  regions?: Maybe<Array<Maybe<SiteDataRegions>>>;
  footer_headline?: Maybe<Scalars['String']['output']>;
  footer_headline_accent?: Maybe<Scalars['String']['output']>;
  footer_subtext?: Maybe<Scalars['String']['output']>;
  contact?: Maybe<SiteDataContact>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteDataHeroFilter = {
  title_line1?: InputMaybe<StringFilter>;
  title_line2?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type SiteDataProblemsFilter = {
  title?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
};

export type SiteDataApproachStepsFilter = {
  number?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
};

export type SiteDataApproachFilter = {
  steps?: InputMaybe<SiteDataApproachStepsFilter>;
  note?: InputMaybe<StringFilter>;
};

export type SiteDataSolutionsFilter = {
  title?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
};

export type SiteDataRegionsFilter = {
  name?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
};

export type SiteDataContactFilter = {
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  whatsapp?: InputMaybe<StringFilter>;
};

export type SiteDataFilter = {
  hero?: InputMaybe<SiteDataHeroFilter>;
  problems?: InputMaybe<SiteDataProblemsFilter>;
  approach?: InputMaybe<SiteDataApproachFilter>;
  solutions?: InputMaybe<SiteDataSolutionsFilter>;
  regions?: InputMaybe<SiteDataRegionsFilter>;
  footer_headline?: InputMaybe<StringFilter>;
  footer_headline_accent?: InputMaybe<StringFilter>;
  footer_subtext?: InputMaybe<StringFilter>;
  contact?: InputMaybe<SiteDataContactFilter>;
};

export type SiteDataConnectionEdges = {
  __typename?: 'SiteDataConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SiteData>;
};

export type SiteDataConnection = Connection & {
  __typename?: 'SiteDataConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteDataConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSiteData: SiteData;
  createSiteData: SiteData;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSiteDataArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteDataMutation;
};


export type MutationCreateSiteDataArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteDataMutation;
};

export type DocumentUpdateMutation = {
  siteData?: InputMaybe<SiteDataMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  siteData?: InputMaybe<SiteDataMutation>;
};

export type SiteDataHeroMutation = {
  title_line1?: InputMaybe<Scalars['String']['input']>;
  title_line2?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type SiteDataProblemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
};

export type SiteDataApproachStepsMutation = {
  number?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
};

export type SiteDataApproachMutation = {
  steps?: InputMaybe<Array<InputMaybe<SiteDataApproachStepsMutation>>>;
  note?: InputMaybe<Scalars['String']['input']>;
};

export type SiteDataSolutionsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
};

export type SiteDataRegionsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
};

export type SiteDataContactMutation = {
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  whatsapp?: InputMaybe<Scalars['String']['input']>;
};

export type SiteDataMutation = {
  hero?: InputMaybe<SiteDataHeroMutation>;
  problems?: InputMaybe<Array<InputMaybe<SiteDataProblemsMutation>>>;
  approach?: InputMaybe<SiteDataApproachMutation>;
  solutions?: InputMaybe<Array<InputMaybe<SiteDataSolutionsMutation>>>;
  regions?: InputMaybe<Array<InputMaybe<SiteDataRegionsMutation>>>;
  footer_headline?: InputMaybe<Scalars['String']['input']>;
  footer_headline_accent?: InputMaybe<Scalars['String']['input']>;
  footer_subtext?: InputMaybe<Scalars['String']['input']>;
  contact?: InputMaybe<SiteDataContactMutation>;
};

export type SiteDataPartsFragment = { __typename: 'SiteData', footer_headline?: string | null, footer_headline_accent?: string | null, footer_subtext?: string | null, hero?: { __typename: 'SiteDataHero', title_line1: string, title_line2: string, subtitle?: string | null } | null, problems?: Array<{ __typename: 'SiteDataProblems', title: string, desc?: string | null } | null> | null, approach?: { __typename: 'SiteDataApproach', note?: string | null, steps?: Array<{ __typename: 'SiteDataApproachSteps', number?: string | null, title: string, desc?: string | null } | null> | null } | null, solutions?: Array<{ __typename: 'SiteDataSolutions', title: string, desc?: string | null } | null> | null, regions?: Array<{ __typename: 'SiteDataRegions', name: string, desc?: string | null } | null> | null, contact?: { __typename: 'SiteDataContact', email?: string | null, phone?: string | null, address?: string | null, whatsapp?: string | null } | null };

export type SiteDataQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteDataQuery = { __typename?: 'Query', siteData: { __typename: 'SiteData', id: string, footer_headline?: string | null, footer_headline_accent?: string | null, footer_subtext?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'SiteDataHero', title_line1: string, title_line2: string, subtitle?: string | null } | null, problems?: Array<{ __typename: 'SiteDataProblems', title: string, desc?: string | null } | null> | null, approach?: { __typename: 'SiteDataApproach', note?: string | null, steps?: Array<{ __typename: 'SiteDataApproachSteps', number?: string | null, title: string, desc?: string | null } | null> | null } | null, solutions?: Array<{ __typename: 'SiteDataSolutions', title: string, desc?: string | null } | null> | null, regions?: Array<{ __typename: 'SiteDataRegions', name: string, desc?: string | null } | null> | null, contact?: { __typename: 'SiteDataContact', email?: string | null, phone?: string | null, address?: string | null, whatsapp?: string | null } | null } };

export type SiteDataConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteDataFilter>;
}>;


export type SiteDataConnectionQuery = { __typename?: 'Query', siteDataConnection: { __typename?: 'SiteDataConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteDataConnectionEdges', cursor: string, node?: { __typename: 'SiteData', id: string, footer_headline?: string | null, footer_headline_accent?: string | null, footer_subtext?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'SiteDataHero', title_line1: string, title_line2: string, subtitle?: string | null } | null, problems?: Array<{ __typename: 'SiteDataProblems', title: string, desc?: string | null } | null> | null, approach?: { __typename: 'SiteDataApproach', note?: string | null, steps?: Array<{ __typename: 'SiteDataApproachSteps', number?: string | null, title: string, desc?: string | null } | null> | null } | null, solutions?: Array<{ __typename: 'SiteDataSolutions', title: string, desc?: string | null } | null> | null, regions?: Array<{ __typename: 'SiteDataRegions', name: string, desc?: string | null } | null> | null, contact?: { __typename: 'SiteDataContact', email?: string | null, phone?: string | null, address?: string | null, whatsapp?: string | null } | null } | null } | null> | null } };

export const SiteDataPartsFragmentDoc = gql`
    fragment SiteDataParts on SiteData {
  __typename
  hero {
    __typename
    title_line1
    title_line2
    subtitle
  }
  problems {
    __typename
    title
    desc
  }
  approach {
    __typename
    steps {
      __typename
      number
      title
      desc
    }
    note
  }
  solutions {
    __typename
    title
    desc
  }
  regions {
    __typename
    name
    desc
  }
  footer_headline
  footer_headline_accent
  footer_subtext
  contact {
    __typename
    email
    phone
    address
    whatsapp
  }
}
    `;
export const SiteDataDocument = gql`
    query siteData($relativePath: String!) {
  siteData(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteDataParts
  }
}
    ${SiteDataPartsFragmentDoc}`;
export const SiteDataConnectionDocument = gql`
    query siteDataConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteDataFilter) {
  siteDataConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteDataParts
      }
    }
  }
}
    ${SiteDataPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      siteData(variables: SiteDataQueryVariables, options?: C): Promise<{data: SiteDataQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteDataQueryVariables, query: string}> {
        return requester<{data: SiteDataQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteDataQueryVariables, query: string}, SiteDataQueryVariables>(SiteDataDocument, variables, options);
      },
    siteDataConnection(variables?: SiteDataConnectionQueryVariables, options?: C): Promise<{data: SiteDataConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteDataConnectionQueryVariables, query: string}> {
        return requester<{data: SiteDataConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteDataConnectionQueryVariables, query: string}, SiteDataConnectionQueryVariables>(SiteDataConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  